apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customers-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-demo
  template:
    metadata:
      labels:
        app: customers-demo
    spec:
      containers:
        - name: customers-demo
          imagePullPolicy: IfNotPresent
          image: localhost:5000/customers-demo:latest
          ports:
          - containerPort: 8900
            name: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8900
            initialDelaySeconds: 1
          readinessProbe:
           httpGet:
            path: /actuator/health/readiness
            port: 8900
           initialDelaySeconds: 5
           periodSeconds: 10

